# Generated by Django 3.2.5 on 2021-07-24 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(default=datetime.datetime(2021, 7, 24, 8, 53, 4, 897714, tzinfo=utc))),
                ('check_in', models.DateTimeField(default=datetime.datetime(2021, 7, 24, 8, 53, 4, 897749, tzinfo=utc))),
                ('check_out', models.DateTimeField(default=datetime.datetime(2021, 7, 24, 8, 53, 4, 897782, tzinfo=utc))),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
    ]
