# Generated by Django 3.2.5 on 2021-07-19 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcomment',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
