# Generated by Django 3.2.5 on 2021-07-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='check_in',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_out',
            field=models.CharField(max_length=30),
        ),
    ]
