# Generated by Django 3.2.5 on 2021-07-19 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_rating_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='mark',
            field=models.FloatField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
