# Generated by Django 3.2.5 on 2021-08-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='href',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
