version: "3"
services: 
    postgres_server:
        build: ./postgres_server
        restart: always
        env_file: ./postgres_server/.env
    pgadmin:
        build: ./pgadmin4
        restart: always
        env_file: ./pgadmin4/.env
        ports: 
            - 7000:7000
        depends_on: 
            - postgres_server
    django_server:
        build: .
        restart: always
        ports: 
            - 5000:5000
        volumes: 
            - .:/usr/src/app
        depends_on: 
            - postgres_server
    flask_hotels:
        build: ./flask_hotels_service
        restart: always
        ports:
            - 5001:5001