version: "3"
services: 
    postgres_server:
        build: ./postgres_server
        restart: always
        env_file: ./postgres_server/.env
    redis_server:
        container_name: redis
        image: redis:alpine
        restart: always
        env_file: django_app/.env
    pgadmin:
        build: ./pgadmin4
        restart: always
        env_file: ./pgadmin4/.env
        ports: 
            - 7000:7000
        depends_on: 
            - postgres_server
    djangoserver:
        build: .
        restart: always
        ports: 
            - 5000:5000
        volumes: 
            - .:/usr/src/app
        depends_on: 
            - postgres_server
            - redis_server
