version: "3"
services:
    pgadmin:
        build: ./pgadmin4
        restart: always
        env_file: ./pgadmin4/.env
        ports: 
            - 7000:7000
    djangoserver:
        build: ./django_app
        restart: always
        ports: 
            - 5000:5000
        volumes: 
            - ./django_app:/usr/src/app
