version: "3"
services: 
    postgres_server:
        build: ./postgres_server
        restart: always
        env_file: ./postgres_server/.env
    redis_server:
        container_name: redis
        image: redis:alpine
        restart: always
        env_file: django_app/.env
    pgadmin:
        build: ./pgadmin4
        restart: always
        env_file: ./pgadmin4/.env
        ports: 
            - 7000:7000
        depends_on: 
            - postgres_server
    djangoserver:
        build: .
        restart: always
        ports: 
            - 5000:5000
        volumes: 
            - .:/usr/src/app
        depends_on: 
            - postgres_server
            - redis_server
    transport_parser:
        build: ./transport_parser
        restart: always
        env_file: ./transport_parser/.env
        ports: 
            - 4500:4500
        depends_on:
            - postgres_server
            - djangoserver
        volumes: 
            - ./transport_parser:/usr/src/app
    flask_hotels:
        build: ./flask_hotels_service
        restart: always
        ports:
            - 5001:5001
        volumes:
            - .:/usr/src/app
    flask_weather:
        build: ./flask_weather_service
        restart: always
        ports:
            - 5002:5002
        volumes:
            - .:/usr/src/app
    statistics_rabbitmq_server:
        build: ./statistics_rabbitmq_server
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
    statistics_mongo_db_server:
        build: ./statistics_mongo_db_server
        restart: always
        env_file: ./statistics_mongo_db_server/.env
        ports: 
            - '27017-27019:27017-27019'
    statistics_mongo_express:
        build: ./statistics_mongo_express
        restart: always
        env_file: ./statistics_mongo_express/.env
        ports: 
            - 8081:8081
        depends_on: 
            - statistics_mongo_db_server
    tg_bot:
        build: ./tg_bot
        restart: always
        ports:
            - 5025:5025
        volumes:
            - ./tg_bot:/usr/src/app
