# Generated by Django 3.2.5 on 2021-07-21 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_name', models.CharField(max_length=300)),
                ('departure_date', models.DateTimeField(default=datetime.date.today, null=True)),
                ('arrival_name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=200)),
                ('blablacar_url', models.URLField(max_length=500)),
                ('parsed_time', models.DateTimeField(default=datetime.date.today, null=True)),
                ('source_name', models.CharField(max_length=500)),
                ('source_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_name', models.CharField(max_length=300)),
                ('arrival_name', models.CharField(max_length=300)),
                ('departure_date', models.DateTimeField(default=datetime.date.today, null=True)),
                ('parsed_time', models.DateTimeField(default=datetime.date.today, null=True)),
                ('source_name', models.CharField(max_length=500)),
                ('source_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(default=None, max_length=300)),
                ('train_number', models.CharField(max_length=200)),
                ('train_uid', models.CharField(max_length=200)),
                ('departure_name', models.CharField(max_length=300)),
                ('departure_code', models.IntegerField()),
                ('departure_date', models.DateTimeField(default=datetime.date.today, null=True)),
                ('arrival_name', models.CharField(max_length=300)),
                ('arrival_code', models.CharField(max_length=300)),
                ('arrival_date', models.DateTimeField(default=datetime.date.today, null=True)),
                ('in_route_time', models.CharField(max_length=200)),
                ('parsed_time', models.DateTimeField(default=datetime.date.today, null=True)),
                ('source_name', models.CharField(max_length=500)),
                ('source_url', models.URLField(max_length=500)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
            ],
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.AddField(
            model_name='car',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route'),
        ),
    ]
