# Generated by Django 3.2.5 on 2021-07-19 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_name', models.CharField(max_length=30)),
                ('departure_date', models.DateTimeField(default=datetime.date.today)),
                ('arrival_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('blablacar_url', models.URLField(max_length=350)),
                ('parsed_time', models.DateTimeField(default=datetime.date.today)),
                ('source_name', models.CharField(max_length=350)),
                ('source_url', models.URLField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_name', models.CharField(max_length=30)),
                ('arrival_name', models.CharField(max_length=30)),
                ('departure_date', models.DateTimeField(default=datetime.date.today)),
                ('parsed_time', models.DateTimeField(default=datetime.date.today)),
                ('source_name', models.CharField(max_length=350)),
                ('source_url', models.URLField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(default=None, max_length=50)),
                ('train_number', models.CharField(max_length=10)),
                ('train_uid', models.CharField(max_length=10)),
                ('departure_name', models.CharField(max_length=30)),
                ('departure_code', models.IntegerField()),
                ('departure_date', models.DateTimeField(default=datetime.date.today)),
                ('arrival_name', models.CharField(max_length=30)),
                ('arrival_code', models.CharField(max_length=30)),
                ('arrival_date', models.DateTimeField(default=datetime.date.today)),
                ('in_route_time', models.CharField(max_length=20)),
                ('parsed_time', models.DateTimeField(default=datetime.date.today)),
                ('source_name', models.CharField(max_length=350)),
                ('source_url', models.URLField(max_length=350)),
            ],
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
